In [22]:
# 3. Fin^ the shape, size an^ ^imension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]3. Fin^ the shape, size an^ ^imension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
import numpy as np
a=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr=np.array(a)
shape=np.shape(arr)
size=np.size(arr)
dim=np.ndim(arr)
print(f'dimesion={dim},size={size},shape={shape}')

dimesion=2,size=12,shape=(3, 4)


In [23]:
# 4. Write python co^e to access the first row of the following array?
import numpy as np
a=[[1, 2, 3, 4]
,[5, 6, 7, 8],
[9, 10, 11, 12]]

arr=np.array(a)
print(arr)
print()
print('here is the first row of array',arr[0])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

here is the first row of array [1 2 3 4]


In [4]:
# 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

a=[[1, 2, 3, 4]
,[5, 6, 7, 8],
[9, 10, 11, 12]]
arr=np.array(a)
print('element at the third row and the fourth  column is =',arr[2,3])

element at the third row and the fourth  column is = 12


In [5]:
# 6. Write co^e to extract all odd-indexe^ elements from the given numpy array?
def odd(numpyarray):
    odd_element=numpyarray[numpyarray %2!=0]
    return odd_element




arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(odd(arr))


[ 1  3  5  7  9 11]


In [46]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
arr=np.random.rand(3,3)
print(arr)

[[0.49819096 0.43066333 0.28984777]
 [0.83329805 0.77635375 0.99782691]
 [0.63476103 0.67710627 0.48340128]]


In [47]:
# 8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?
import numpy as np
rand_array = np.random.rand(2, 3)
rand_array2=np.random.randn(2,3)
print(rand_array)
print(rand_array2)


[[0.64850858 0.40849286 0.21066275]
 [0.56717544 0.76992944 0.85228518]]
[[-0.43114163 -0.5027118   0.06879506]
 [-0.90239421  1.43377141 -0.24161435]]


In [39]:
# 9. Write co^e to increase the ^imension of the following array?
a=np.array([[1, 2, 3, 4]
,[5, 6, 7, 8],
[9, 10, 11, 12]])
reshape=np.expand_dims(a,axis=0)
print(reshape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [40]:
# 10. How to transpose the following array in NumPy?
a=np.array([[1, 2, 3, 4]
,[5, 6, 7, 8],
[9, 10, 11, 12]])
transpose=np.transpose(a)
print(transpose)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [41]:
# 11. Consi^er the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python1
# ,+ I(dex wiLe multiplicatio'
# ]+ Matix multiplicatio'
# + Add both the maticK
# -+ Subtact matix B om 
# + Diide Matix B by A
MatrixA2 =np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB2= np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
im=MatrixA2 * MatrixB2
# mm=MatrixA2 @ MatrixB2 
a= MatrixA2 + MatrixB2
s= MatrixB2 - MatrixA2
d= MatrixB2 / MatrixA2
print(f'here is the indexwisemultiplication={im},here is the addition of array{a},here is the substraction of the array{s},here is the division of array{d}')

here is the indexwisemultiplication=[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]],here is the addition of array[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]],here is the substraction of the array[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]],here is the division of array[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
# 12. Which function in Numpy can be used to swap the byte order of an array?
arr=np.array([1,2,3,4],dtype=np.int32)
swapped=arr.byteswap()
print(swapped)


[16777216 33554432 50331648 67108864]


In [43]:
# 13. What is the significance of the np.linalg.inv function?
A = np.array([[2, 3],
              [1, -2]])

b = np.array([5, 3])
inv=np.linalg.inv(A)
x=np.dot(inv,b)
print(x)

[ 2.71428571 -0.14285714]


In [44]:
# 14. What ^oes the np.reshape function ^o, an^ how is it use^?
# reshape= the numpy function which is used to change the dimension(shape) while maintaining the underlying data and the element which are present in array get recognised in new shape 

arr=np.array([[[[[3,4,5,6],[5,1,2,3],[9,7,5,5]]]]])
print(np.ndim(arr))
re=np.reshape(arr,(1,1,1,1,1,1,3,4))
print(re)

5
[[[[[[[[3 4 5 6]
       [5 1 2 3]
       [9 7 5 5]]]]]]]]


In [45]:
# 15. What is broa^casting in Numpy?
#broad casting is the mechanism which allows to perform the arthematic operation on the arrays of different shape
arr1=np.array([[2,3,5,1],[4,5,6,7]])
arr2=np.array([1,2,3,4])
s=arr1 + arr2
print(s)

[[ 3  5  8  5]
 [ 5  7  9 11]]


In [48]:
# 1. What is a Python library? Why ^o we use Python libraries?
# python libraries are the pre written codes that cam to use in various programs we create
# it provide the extended functionality of the tools and fucntions , it contains the advanced 
# fucntion classes which save our time and not let us write the pre written function from scratch


In [ ]:
# # 2. What is the ^ifference between Numpy array an^ List?
# list is a data structure which can store homogenous and hetrogenous elements like string interger 
# float ect
# while numpy array is the mathematical provided data structure which only stores homogenous elements which are int and float 
# which makes numpy array more faster than the list